LightTable/LightTable

src/lt/objs/editor.cljs
Leverage CM's ruler addon to provide a behavior to add rulers - [screenshot](https://www.dropbox.com/s/ipq7c21w1dkwmg3/Screenshot%202015-01-24%2011.50.25.png?dl=0). Users can use it as follows:
```clojurescript
;; Draw a ruler at 80 chars
[:editor :lt.objs.editor/set-rulers]
;; Or specify multiple rulers
[:editor :lt.objs.editor/set-rulers [{:lineStyle "dashed" :color "#aff" :column 80}
{:lineStyle "dashed" :color "#aff" :column 120}]]
```
Will merge this on monday unless there are concerns.
=> Add behavior to use CM rulers - close #892

src/lt/objs/clients/local.cljs
Found/fixed during hack night.
CSS files being evaluated are injected as a style tag with an id derived from the file name; the derivation was not properly escaping any characters besides `.`, such as ` `.
=> Fix css injection-eval filename escaping.

src/lt/objs/editor/pool.cljs
I wrote a comment about this bug(maybe bug...) in the end of this issue(#1810).
I did two things.
- fix a bug.
- add message notifying wrap on and off to indicate which one is done.
=> fix a bug of :editor.force.wrap command

script/build-app.sh, script/build.sh, script/light.sh, shell/.gitignore, shell/Gruntfile.js, shell/package.json
Github has changed the name of atom-shell to electron as per
https://github.com/atom/electron/pull/1389
=> Update build scripts for atom-shell name change to electron

.gitattributes
The build fails on Windows if the Git `core.autocrlf` configuration setting is `true` – see issue #1924.
@rundis Thoughts?
=> Add Git attributes file to disable auto-CRLF conversion for all text files.

src/lt/objs/deploy.cljs, src/lt/objs/plugins.cljs
Fixed so that downloading of plugins verifies that download succeeds before trying to untar. #1789 indicated that the error was in the gunzip/untar phase, but the problem was really that the download failed and the error response was streamed to file for then to be unzipped etc.. no wonder that failed.
In addition another fix was made. If people add a suffix of .git to the :source attribute in their plugin.edn or plugin.json, the download of plugin tar also fails. Must have worked previously, but apparently not any longer. Anyways any .git to the source path is now stripped off.
=> Better handling of #1789 - Plugin download errors now handled.

src/lt/objs/plugins.cljs
Quickfix for misleading message when installing plugins. 
The fix only verifies that the plugin map is a seq (not empty/nil). The real fix I guess is to figure out why one of the supposed plugins is an empty map. To much going on in plugins.cljs for me to figure out the proper fix right now.
=> Fixes #1727 Invalid behaviors file

script/build-app.sh
Zip release files after app build for Windows.
@cldwalker @rundis I finally got around to this. The existing archive files referenced by the "download" links on the home page all contain a *LightTable* directory. The zip file produced by these changes will contain a directory named like *lighttable-0.8.0-windows* (which is fine with me).
I'll merge this if no one objects in a day or two.
=> Optionally zip release files after app build (for Windows).

src/lt/objs/browser.cljs
@rundis I was able to replicate the issue by opening and closing a browser tab or with your instructions. Since the clear-console command looks for [all devtools-client objects](https://github.com/LightTable/LightTable/blob/1d9dd0cc3154048834aedd554a056acb0a2df127/src/lt/objs/console.cljs#L255) and tries to communicate with them, it makes sense to destroy the browser's devtools object when the browser object was destroyed.
=> Destroy devtools-client along with parent browser - close #1975

src/lt/objs/settings.cljs
While trying to use the workspace behaviors command, I noticed it was buggy and out of date. Buggy because opening it kicked off incorrect dialogs about file being deleted or prompting to save to a file. Neither of these are correct as workspace behaviors are saved to the current-workspace object.
After this was fixed, I noticed that workspace.behaviors doesn't support the flat format. Given that all docs point to the new format and that autocompleting behaviors only works for the flat format, I fixed this. While fixing this I verified there are only two places where we need to convert/parse :ws-behaviors - when saving them and when loading them when LT starts up
@rundis @kenny-evitt Could I get one off of you to sign off?
=> Fix workspace behaviors

src/lt/objs/plugins.cljs
@kenny-evitt @rundis This fixes the long-standing bug with an installed plugin not showing new behaviors, commands and keymap :) @kenny-evitt You should be able to install Vim as you did on the issue you filed and just have it work. Fix explained in commit
=> Fix installing a plugin doesn't load new behavior- close #1970

src/lt/objs/plugins.cljs
@kenny-evitt @rundis This fixes #1944 which I had thought was fixed back in 7b3ebf1a768d835b195c59b620d0cbd512de8349. I also cleaned up `available-plugins` as having the options dynamic in one place and hardcoded in another was making this confusing to read. By breaking them into more smaller usable chunks less option passing is needed. When QAing, I tried edge cases like deleting a plugin directory and then seeing if the manager would prompt me to install it
=> Fix uninstall message

deploy/core/package.json, deploy/core/version.json, project.clj, script/build.sh
@cldwalker @rundis FYI
Plugins with changes not included in the latest version:
- [Paredit](https://github.com/LightTable/Paredit/commits/master)
- [CSS](https://github.com/LightTable/CSS/commits/master)
- [HTML](https://github.com/LightTable/HTML/commits/master)
=> Bump default plugin versions

script/build-app.sh
I didn't like the tarball contents all being under an extraneous *builds* directory.
I'm going to rebase recent changes so this merges cleanly.
=> Remove extraneous 'builds' directory in tarball contents.

src/lt/objs/eval.cljs
Ensure inline results are cleared when evaling lines where col for result is offset from previous eval result Addressing - #2004
Seems to still work as expected with instarepl and watches as well.
=> Fix results stacking of inline-results for normal eval

deploy/settings/default/default.behaviors, src/lt/plugins/auto_complete.cljs
Hi guys!
I decided to address a beginner-level bug. Not sure about `remove-long-completitions` function name and everything else to be honest.
Best,
Dmitriy
=> Implement a hint length limit for auto-complete #1635

src/lt/objs/plugins.cljs
Previously `build-cache` was attempting to sort plugin versions but [`sort-by`](https://clojuredocs.org/clojure.core/sort-by) was being called with the version comparator being passed as the sort key function. The version comparator was also inverting the standard return values for a comparator – see [`compare`](https://clojuredocs.org/clojure.core/compare) for an example.
=> Fix version sorting for building plugin cache data. Fixes #2043

deploy/core/User/user.behaviors, deploy/core/User/user.keymap, doc/behavior-and-keymap-configuration.md, src/lt/objs/menu.cljs
Over the past couple weeks, I've had some designers (non backend people) at my coworking space trying out LightTable. The feedback was pretty consistent in that user.keymap and user.behaviors explanations were confusing (they don't know what diffs and objects are). To address this I revamped the user.keymap and user.behaviors explanations to be more practical and created a separate document for describing configuration in detail. I also added menu items for functionality users were looking for but not finding since they weren't familiar with the command pane. Even when they found the command pane, these new users preferred to access them through the menu. Given configuration/settings and the plugin manager are integral parts of using LightTable, I think adding them to the menu will help …
=> Improve new user experience

src/lt/objs/sidebar/workspace.cljs, src/lt/util/dom.cljs
In a project with a deeply nested folder structure, renaming the file results in a very small input. This ensures the input is at least as wide as the filename being edited.
There is also a visual change to that maintains the highlight width consistent even when the sidebar needs to scroll.
=> Set width of inputs / files in sidebar

src/lt/objs/cli.cljs
This fixes #2053 in a clean way. I originally tried 6cbc2d6c813ca36013f819e2383fa98f0faeb8ba but I think checking for a stringified Apple event is brittle and error-prone. I [verified upstream with Electron](https://github.com/atom/electron/issues/3657) that this an expected behavior when opening a file from a file manager in osx. I verified that changing ordering of arguments doesn't effect opening files from the commandline in osx and linux
@rundis @kenny-evitt I'll leave this open till Friday and then merge unless there are any concerns
=> Fix opening file from osx file manager - close #2053

src/lt/objs/editor.cljs, src/lt/objs/editor/pool.cljs
BTW in 6cf6d31b37dfaf52c4f0a48f97c32114b60d729a @brabadu modified a bunch of normal functions to arity-overloaded functions in order to get rid of some warnings by passing nil as a default parameter. I think this way we just stash away the warnings without properly resolving them. IMO it would be better to leave the warnings displayed until someone gets irritated enough (as I got) and fixes the warnings properly, just as I did in this patch.
=> DRY: comment/uncomment/toggle-comment

deploy/core/version.json, deploy/electron/Gruntfile.js, doc/developer-install.md, doc/for-committers.md
Doing the upgrade because our auto-updating notification doesn't work from 0.x.x-alpha to 0.x.x. Also we're doing a full QA for 0.8.0, so we may as well pull in upstream bug fixes with an upgrade.
Held off on upgrading to 0.35.0 since there are ipc changes to handle. Also worth noting that https://github.com/atom/electron/releases/tag/v0.33.4 moved devtools-* events. Our code still works fine for now but something we'll eventually want to change
I ran through about 1/2 the QA checklist on OSX and found no new issues. @rundis @kenny-evitt Could one of you try some of the QA on linux or windows? We can always revert this if it fails our full QA
=> Upgrade to Electron 0.34.5

README.md, doc/for-committers.md, project.clj, script/build-api-docs.sh, src/lt/macros.clj, src/lt/object.cljs, src/lt/objs/command.cljs, src/lt/objs/editor.cljs, src/lt/objs/editor/pool.cljs, src/lt/objs/files.cljs, src/lt/objs/notifos.cljs
This adds API docs for LightTable building off of https://github.com/LightTable/LightTable/commit/f94bf3af0d382424c69161d5b01680d0ea657a38 so we can encourage plugin authors and more users to read and understand the code base. I've included a script and documentation for publishing these docs. [Here is what the current docs look like](http://lighttable.github.io/LightTable/api/lt.macros.html). The styling isn't amazing but I'm ok with for a first pass. I did have to mark some fns private and added a few more docstring for public fns. I limited docs to a few namespaces as covered in #1955. I'm open to adding more down the road.
There weren't too many choices when choosing between libraries that generate documentation for cljs projects: I only found codox and marginalia. I chose codox …
=> Add api docs

.gitignore, cljsdeps/core.cljs, deploy/core/node_modules/clojurescript/cljsDeps.js, project.clj, src-cljsdeps/core.cljs, src/lt/objs/cli.cljs, src/lt/objs/clients/devtools.cljs, src/lt/objs/clients/tcp.cljs, src/lt/objs/clients/ws.cljs, src/lt/objs/editor.cljs, src/lt/objs/eval.cljs, src/lt/objs/langs/behaviors.cljs, src/lt/objs/langs/keymap.cljs, src/lt/objs/plugins.cljs, src/lt/objs/sidebar/navigate.cljs, src/lt/objs/workspace.cljs, src/lt/util/cljs.cljs, src/lt/util/dom.cljs, src/lt/util/load.cljs
Unlike previous attempts, this PR only address upgrade todos for #1973 that are compatible with the current version of ClojureScript. By doing this upfront work, we make the upgrade branch more manageable and closer within reach :smile: . This PR does the following:
* Fixes all clojurescript warnings that future versions of lein-cljsbuild will pick up. These are warnings that we shouldn't be causing anyway so these are uncontroversial.
* This introduces a second build target for generating cljsDeps.js as done by @BenjaminVanRyseghem in #1952. Having a second build target can introduce unreliability in `lein cljsbuild once`. I'll double check to see if I need to update script/build.sh in some way. This build target only needs to be run when we upgrade cljs.
* Remove our dependence on …
=> Prelude to clojurescript upgrade

src/lt/objs/plugins.cljs
When saving clojure.cljs in the Clojure and rebuilding a plugin's clojurescript, we are
unnecessarily opening nonexistent files. We didn't notice this before because we weren't logging those errors until dffe186953b6be27b7ba1ee402d8bc0a94f6626f e.g. `Failed to open path '/Users/me/Library/Application Support/LightTable/plugins/Clojure/plugin.json' with error:`. I searched the rest of the code base and didnt' find any other uses of files/open-* that were effected in a similar way. Will merge this tomorrow unless there are any concerns
=> Avoid opening a nonexistent file and logging error

src/lt/objs/deploy.cljs, src/lt/objs/plugins.cljs
This fixes #2026. I was able to consistently reproduce the error by turning off the internet connection
and starting LightTable. Now when a user experiences this error, they see:
```
Invalid JSON response from https://api.github.com/repos/LightTable/LightTable/tags: ""
Failed to load resource: net::ERR_INTERNET_DISCONNECTED: https://api.github.com/repos/LightTable/LightTable/tags
```
The first commit explains why we can't detect on response code and I think this is a reasonable solution given the time spent on it. I also searched for other similar uses of fetch/xhr  and found the plugin manager would cause the same error when the network was off.
@rundis @kenny-evitt I'll merge tomorrow unless there are any concerns
=> Handle invalid tags and metadata-commits responses

deploy/settings/default/default.behaviors, src/lt/objs/document.cljs, src/lt/objs/editor/pool.cljs
This fixes #942 and #1720 - usability issues with files being modified and deleted when doing git (or any vcs) operations outside LightTable. Previously, when a file was modified or deleted externally, we would display a popup on each tab and display multiple popups on each tab for each time the file was modified. This was painful as switching or merging branches often led to clicking on a number of dialogs. The new behavior mimics Atom which I think is more friendly and intuitive. The new behavior for a modified file with unsaved changes is to leave the tab as is. As explained in the commit, a user will still get a dialog on save which prevents accidental overwrite. The new behavior for a deleted file is to remove its tab if there are no unsaved changes and to leave the tab as is if …
=> Improve usability with git and any other vcs

src/lt/objs/editor.cljs, src/lt/objs/editor/file.cljs, src/lt/objs/editor/pool.cljs
As pointed out in #1733, there is a bug where the tab doesn't update when trailing whitespace is removed. Fix involved adding a new editor function as CodeMirror's setValue doesn't keep cursor position. Also fixed a related bug where cursor position always jumped when file was modified outside LT. Now there's a fix where cursor position is kept for cases explained in commit. To QA, open a file, move cursor somewhere, `touch FILE` in terminal and observe cursor stay put.
@rundis @kenny-evitt Merging tomorrow night unless there are any concerns
=> Fix editor save behaviors

src/lt/objs/files.cljs, src/lt/objs/sidebar/workspace.cljs
Latest fs has a rename that is case sensitive. Exists check wasn't case sensitive on osx but able
to work around that by checking if case differs
@rundis @kenny-evitt Will merge later today unless there's a concern
=> Allow case sensitive renaming - close #1352

src/lt/objs/style.cljs
Users have been mislead in #1460 and #1045 by "Editor:" in the font-settings behavior description. Changing to "App: " makes it clear this is global. Will merge this later today unless there's a concern
=> Font settings is global, not editor specific - #1460

deploy/core/css/skins/new-dark.css, deploy/core/css/skins/new-dark.stylus, deploy/core/css/structure.css, deploy/settings/default/default.behaviors, src/lt/objs/docs.cljs
Agree that documentation should have navigation so moved it into a browser tab. Removed a bunch of custom code around setting up and styling a custom doc iframe. Documentation no longer opens in a tabset as it was buggy and I don't think provided much value. Before the change:
After the change - looks the same but is much more usable:
The doc namespace is just the command but I couldn't think of somewhere else to put it. 
@kenny-evitt @rundis I'll merge Saturday unless there are any concerns
=> Make docs navigable by opening in a browser tab - close #1097

deploy/settings/default/default.keymap, src/lt/objs/sidebar/clients.cljs
:show-connect command is a toggle command. Removed :hide-connect since
that command closes the connection bar correctly in the only context
it's used. It's tempting to rename :show-connect to :toggle-connect but I didn't want to cause any command breakages.
@kenny-evitt @rundis Merging tomorrow unless there are concerns
=> Just have a toggle connect command - close #1167

src/lt/objs/tabs.cljs
Fix wasn't the most obvious but I confirmed it works on my ubuntu box. Merging later unless there's a concern
=> Middle click tab close should not paste on linux - close #1816

deploy/settings/default/default.behaviors
Fixes 4 file types we weren't syntax highlighting. I verified each one works. [Demo of the mode](https://codemirror.net/mode/htmlembedded/index.html) and [location of where mime types are defined](https://github.com/LightTable/HTML/blob/3454302ec2f0fc59205bd2da95ed9f504d621005/codemirror/htmlembedded.js#L70-L73). Merging tomorrow unless there are concerns
=> Add 4 file types for htmlembedded mode - close #1883

script/build.sh
This fixes the Bash file existence check so it handles paths with spaces on Windows.
=> Quote `which` command in build script

deploy/settings/default/default.behaviors, src/lt/objs/editor.cljs
Add enable/disable behaviors codemirror edit/closebrackets.js addon, that fix pairs autocomplete for international keyboards.
For more information see #2003
=> #2003 Add behaviors to enable/disable edit/closebrackets.js addon.

src/lt/objs/editor/file.cljs
#2097 restored cursor but forgot to restore scroll. 
You can recreate the bug by going to the middle of a big file [e.g. settings.cljs](https://github.com/LightTable/LightTable/blob/02e968f869dad546aeb27b7076e993c4a4531727/src/lt/objs/settings.cljs#L229) and putting the cursor in the middle of the screen. Add some whitespace to the end of the line and press save. While the cursor is preserved, the scroll position is lost and the cursor is dropped to the bottom of the screen.
Going out with tomorrow's release unless there are concerns
=> Fix scroll position jumping on save after stripping whitespace

src/lt/objs/plugins.cljs
=> Exclude the 'script' sub-directory when building the plugin metadata cache

doc/developer-install.md
A contributor – @carocad – just ran into the issue covered by #1931 and mentioned it on [the Gitter room](https://gitter.im/LightTable/LightTable). A brief note in the 'developer install' doc seems like it might be helpful to others in the future.
=> Add note about installing additional Node.js package for Debian-based Linux distros

doc/for-committers.md, project.clj
Implements #2202 
Updates codox to a version that makes use of {verison} in :codox :source-uri
Removes references about updating the version in :codox :source-uri for the committers doc
=>  Update 'for committers' doc regarding building API docs and LT version #2202 

doc/for-committers.md, doc/style-guide.md
This is pull request adds the LightTable Style Guide to our docs folder per issue #2236. At the moment, the document is small and primarily points to the [Clojure Style Guide](https://github.com/bbatsov/clojure-style-guide) as it is comprehensive and popular.
It should be expected that our style guide will expand over time to cover various areas unique to LightTable, such as Behaviors, Objects, and Tags.
Please feel free to add to the guide!
=> Add initial LightTable Style Guide document - close #2236

doc/for-committers.md
[Magnus pointed out that removing a Node.js package from the LT core source might affect plugins.](https://github.com/LightTable/LightTable/pull/2238#issuecomment-239687875) I (stupidly) didn't think of that.
I think I should also add a checklist item to review changes for a release and check for any that remove Node.js packages so that users can be notified of the change as described in the note I added already for this PR.
=> Add note about removing a Node package.

doc/for-committers.md
See #2254 and #2170, which inspired the former.
=> Add info about whole-file eval for Light Table source files to 'committers' doc.

doc/for-committers.md, doc/style-guide.md, project.clj, src/lt/objs/editor.cljs, src/lt/objs/files.cljs
This pull request adds documentation to editor and files namespaces. 
One thing to note is that this pull request enables markdown for Codox. This means toggling docs within LightTable will likely cause the markdown syntax to be rendered. A follow up issue #2250 has been opened for future work to address this.
=> Add documentation to editor and files namespaces - closes #2060

deploy/settings/default/default.behaviors, src/lt/plugins/doc.cljs
To test the fix for #2258, open a file, place the cursor within the file, access the language docs sidebar, then close the sidebar. Cursor should return to previous location. 
By default Ctrl shift d opens the language docs sidebar.
=> Fix language docs sidebar from keeping focus when closed - fixes #2258

src/lt/util/dom.cljs, src/lt/util/events.cljs, src/lt/util/ipc.cljs, src/lt/util/js.cljs, src/lt/util/kahn.cljs, src/lt/util/load.cljs, src/lt/util/style.cljs
This PR handles the documentation of the files under the util directory:
- cljs.cljs
- dom.cljs
- events.cljs
- ipc.cljs
- js.cljs
- kahn.cljs
- load.cljs
- style.cljs
One thing to consider is if we should adjust our project.clj to allow for these namespaces to be generated with Codox. Currently, we have only a small number of namespaces exposed.
See issue #2264
=> Document functions of util namespaces - closes #2264

src/lt/objs/files.cljs
This PR removes the -f parameter from shell's rm command in files/delete!. As @cldwalker noticed, it is not needed and could be a potential source of trouble.
=> Remove unnecessary, and potentially dangerous, -f from delete! function.

src/lt/macros.clj, src/lt/object.cljs, src/lt/plugins/doc.cljs
This pull request adds an optional docstring to `defui`, `behavior`, and `object` for issue #2206. It is viewable by the in-line doc command (Ctrl-D). The key to use is `:doc` for behaviors and objects. defui is similar to defn.
One caveat is that the docstrings for behaviors and objects will not appear in Codox. This should not be an issue as behaviors and objects do not currently appear in Codox either... Behaviors likely won't be visible in Codox unless their internal functions are made public, which is probably a bad idea. Objects have a similar issue.
Here are samples:
Do note, this issue does not deal with tags or triggers... so using Ctrl-D on trigger `:close!` rather than the behavior `::close!` will result in no docs found. I do not feel that adding logic to get behavior or …
=> Add optional docstring to defui, behavior, and object - closes #2206

src/lt/objs/plugins.cljs
* Change the `source` button to `website`.
* Clicking the title of a plugin will open the `source` page.
=> Plugin manager changes.

doc/style-guide.md
Simply documents an undocumented convention.
=> Update style guide to define expected :desc convention

src/lt/objs/cache.cljs
This PR makes sure `.../ltcache/default.clj` exists before attempting to open it and fixes issue #2150 
To test:
- Pull down this PR's branch
- Delete or move the default.clj in your LT user directory
- Build and launch LT
- Confirm there is no longer an error on startup
=> Prevent error when launching LT for the first time - fixes #2150

deploy/settings/default/default.behaviors, src/lt/objs/deploy.cljs
Implements #2212.
@kenny-evitt as I didn't hear anything more from you on the issue, I went ahead and implemented my suggestion. Let me know what you think.
=> Add behaviors to enable setting `strictSSL` option for file downloads #2212

deploy/core/node_modules/lighttable/ui/dragdrop.js
Some scaffolding around drag and drop dataTransfer objects was causing LightTable/LightTable#2342
I've just taken the problematic code out and not replaced it with anything.
=> Remove unused dataTransfer code from dragdrop.js
