- README.md
@ibdknox My employer wanted some mention for providing friday contributions for LightTable. This seem reasonable?
> Add credits to readme

- deploy/settings/default/default.behaviors
As described in the #1796 issue, I added all definitions
> Added file types for codemirror modes

- deploy/settings/default/default.keymap
This is the flattened pull request for the toggle comment
> comment toggle with pmeta-/

- script/build-app.sh
- script/build.sh
- script/light.sh
- shell/.gitignore
- shell/Gruntfile.js
- shell/package.json
Addressing Linux-specific references in pull request #1892.
> Electron name change: update for Linux references

- doc/developer-install.md
> Added precondition section for Linux build on atom-shell

- script/light.sh
> Quotes `pwd` to support spaces in path

- doc/developer-install.md
Added a prerequisite section and removed the installation instructions for Leiningen
> Slightly clean up developer install doc

- src/lt/objs/deploy.cljs
Minor cleanup I should've done with #1957
> Forgot to update process.versions when updating to newer electron

- CONTRIBUTING.md
- doc/for-committers.md
- script/build-app.sh
- script/build.sh
Basically fixing our release script so it's just one command - noticed this after our last release. Also added checklist from #1936 and made an unrelated contributing.md tweak. Will merge in a day or two unless I hear any objections
> Script release

- src/lt/objs/clients/ws.cljs
Try to use a hard-coded port, 5678, and only ask
for a random free port when it is not available.
Users that have only one connection thus get by
most of the time without having to change the port
in their HTML whenever LT restarts.
I think it is also better to log errors than to
swallow them.
I am, of course, open to discussions.
> External Browser: Try a default port for socket.io first

- deploy/core/package.json
- deploy/core/version.json
- project.clj
- script/build.sh
Bump version for the next release.
> Bump LT version to *0.8.0*

- deploy/core/changelog.md
- doc/for-committers.md
- project.clj
I took what we had from the alpha release changelog and added a few more bullet points since then.
@kenny-evitt @rundis Can I get a thumbs up?
> Add changelog for 0.8.0

- .travis.yml
@kenny-evitt @rundis Nothing too surprising here. Will merge tomorrow
> Core team should be getting notifications

- src/lt/objs/deploy.cljs
> Decrease new-version check frequency from every five minutes to every hour

- script/build.sh
Signed-off-by: Ryan P.C. McQuen <ryan.q@linux.com>
> use `which` for npm and lein check

- deploy/core/css/structure.css
I'd also been annoyed by the lack of scrolling when opening files. @rundis @kenny-evitt I'll merge tomorrow night unless there are any concerns
> Horizontal scroll on navigator for wide item in list - close #1891

- src/lt/objs/plugins.cljs
@kenny-evitt I followed up on your idea to make plugin actions less confusing. I also added it to uninstall and update for consistency. I'll merge Friday if I don't hear back. Example screenshot:
> Give user feedback when plugin is (un)installed/updated - close #1920

- src/lt/object.cljs
- src/lt/objs/animations.cljs
- src/lt/objs/app.cljs
- src/lt/objs/browser.cljs
- src/lt/objs/canvas.cljs
- src/lt/objs/clients.cljs
- src/lt/objs/clients/local.cljs
- src/lt/objs/clients/tcp.cljs
- src/lt/objs/clients/ws.cljs
- src/lt/objs/document.cljs
- src/lt/objs/files.cljs
- src/lt/objs/jump_stack.cljs
- src/lt/objs/keyboard.cljs
- src/lt/objs/langs/behaviors.cljs
- src/lt/objs/langs/keymap.cljs
- src/lt/objs/opener.cljs
- src/lt/objs/proc.cljs
- src/lt/objs/sidebar/clients.cljs
- src/lt/objs/sidebar/navigate.cljs
- src/lt/objs/statusbar.cljs
- src/lt/objs/style.cljs
- src/lt/objs/thread.cljs
- src/lt/objs/version.cljs
- src/lt/objs/workspace.cljs
This fixes the weirdly indented behaviors that have been scattered across LT's codebase. You can verify this is only whitespace changes by checking out the branch and `git diff -w master`. You shouldn't see any output as `-w` removes any whitespace changes.
@kenny-evitt @rundis Merging tomorrow night unless there are any concerns
> Fix behavior indentation - close #1986

- src/lt/objs/opener.cljs
Straightforward fix for #1427. Will merge tomorrow night unless there are concerns
> open-path should open existing tab for same relative file - close #1427

- src/lt/objs/intro.cljs
- src/lt/objs/menu.cljs
Added access keys and close + about LT menu item for linux and windows per #1143. Also updated menu items to use role attributes instead of deprecated selector ones and remove stale TODOs I noticed while updating menu. I've QAed that effected menu items work on osx and linux
@kenny-evitt @rundis Will merge tomorrow unless there are any concerns
> Menu improvements

- doc/behavior-and-keymap-configuration.md
Improving docs to explain resolution in #1379. Will merge later tonight, tuesday night, unless there are any concerns
> Document keybindings with multiple extensions - close #1379

- deploy/settings/default/default.keymap
Two zoom keys to be compatible w/ chrome + firefox. A user had already contributed these so I just cherry picked. Will merge later today unless there are concerns
> Add zoom keys - close #1741

- deploy/settings/default/default.behaviors
- src/lt/objs/eval.cljs
Also implemented copy for doc underline-result since menu has copy + result
but copy wasn't implemented
Will merge on Saturday unless there are any concerns
> Add menu for underline-result - close #2161

- doc/for-committers.md
cf https://github.com/LightTable/LightTable/issues/2133#issuecomment-244558605
> Chocolatey step

- deploy/settings/default/default.behaviors
For more information see #1903
> #1903 Fixed default.behaviors file.ignore-pattern

- src/lt/objs/editor.cljs
- src/lt/objs/files.cljs
Corrects various typos that have been discovered.
> Fix typos in documentation

- deploy/settings/default/default.keymap
- src/lt/objs/cli.cljs
- src/lt/objs/find.cljs
- src/lt/objs/search.cljs
> Replaces goto with go-to for consistency

- src/lt/plugins/doc.cljs
This PR adds a parameter label field to the in-line doc for behaviors and objects for #2281. If there are no parameters with labels listed in the map then the line is omitted.
Below is an image showing a behavior with a parameter map and corresponding parameter labels:
> Add label field to the inline doc for behaviors and objects - fixes #2281

- doc/developer-install.md
Just noticed a small typo in the developer-install doc!
> Bump version in Usage section to 0.8.1

- deploy/core/css/structure.css
- src/lt/objs/plugins.cljs
> For Issues#2294

- .gitignore
- deploy/core/css/structure.css
Enhancement to select text in Plugin Manager view
See issue https://github.com/LightTable/LightTable/issues/2178
Also modified .gitignore file to ignore IntelliJ's internal files.
> Select text in Plugin Manager

- deploy/core/css/structure.css
Resolves #2286 with a single line added to structure.css.
> Fix Control Pane's arrow direction

- src/lt/objs/files.cljs
Related to https://github.com/LightTable/LightTable/issues/2361
> [#2361] files/folders which directly match svn and cvs keywords are ignored

- deploy/core/main.js
- deploy/core/package.json
- script/build.sh
- src/lt/objs/cli.cljs
This targets the WIP `electron-update` branch and will be eventually merged into it. #2259
> Replace optimist with yargs

- src/lt/util/kahn.cljs
> fix typo Khan -> Kahn
